[project]
name = "full-transaction-sketch"
authors = ["Team Full Transaction"]
description = "A comprehensive blockchain-based transaction orchestration and verification framework"
telemetry = false
requirements = []

[contracts.transaction-coordinator]
path = "contracts/transaction-coordinator.clar"
depends_on = []

[contracts.fund-allocator]
path = "contracts/fund-allocator.clar"
depends_on = []

[contracts.governance-registry]
path = "contracts/governance-registry.clar"
depends_on = []

[contracts.verification-protocol]
path = "contracts/verification-protocol.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
